apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-fastapi-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-fastapi-app
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
      labels:
        app: my-fastapi-app
    spec:
      containers:
      - name: my-fastapi-app
        # Use your specific image from Docker Hub
        image: jeshwanthsingh/my-fastapi-app:1.0
        env:
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://tempo.monitoring:4317"
        - name: OTEL_SERVICE_NAME
          value: "my-fastapi-app"
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: my-fastapi-app-service
  labels:
    app: my-fastapi-app
spec:
  selector:
    app: my-fastapi-app
  ports:
  - name: http
    port: 8000
    targetPort: 8000
