apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource
  namespace: monitoring
  labels:
    grafana_datasource: "1"
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-operated.monitoring:9090
        isDefault: true
      - name: Loki
        type: loki
        access: proxy
        url: http://loki.monitoring:3100
        jsonData:
          derivedFields:
            - datasourceUid: tempo
              matcherRegex: 'traceID=(\w+)'
              name: TraceID
              url: 'http://tempo.monitoring:3200/trace/${__value.raw}'
      - name: Tempo
        type: tempo
        access: proxy
        url: http://tempo.monitoring:3200
        jsonData:
          tracesToLogs:
            datasourceUid: loki