apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: my-fastapi-app-servicemonitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: my-fastapi-app
  endpoints:
  - port: http
